<template><div><p><img src="/images/ldap01.png" alt="LDAP Configuration"></p>
<p>Fill in the LDAP-related information in the Management -&gt; Settings page.</p>
<p><strong>If enabling ldaps, please check the &quot;Enable ldaps&quot; checkbox.</strong></p>
<div class="hint-container tip">
<p class="hint-container-title">Tips</p>
<p>Please fill in the LDAP_Search filter according to your actual situation. Notably, placeholders in Yearning use <code v-pre>%s</code>. As shown in the image above, if filtering by <code v-pre>cn</code>, use <code v-pre>(&amp;(cn=%s))</code>.</p>
<p>Enter the relevant test user's password to test LDAP authentication.</p>
</div>
<h2 id="ldap-user-attribute-mapping" tabindex="-1"><a class="header-anchor" href="#ldap-user-attribute-mapping"><span>LDAP User Attribute Mapping</span></a></h2>
<p>Use attribute mapping to associate attribute information from LDAP with Yearning user data, such as department, email, and real name.</p>
<p>Currently, it supports the mapping of three fields: <code v-pre>real_name</code> (real name), <code v-pre>email</code> (email), and <code v-pre>department</code> (department). For example, if the <code v-pre>name</code> field in ldap user information corresponds to the real name, the <code v-pre>dept</code> field corresponds to the department, and the <code v-pre>mail</code> field corresponds to the email, the mapping format is as follows (key is the user field to be mapped, value is the key value of the corresponding LDAP attribute):</p>
<div class="language-json line-numbers-mode" data-ext="json" data-title="json"><button class="copy" title="Copy code" data-copied="Copied"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">{</span><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577"> "</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">real_name</span><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">name</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577"> "</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">email</span><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">mail</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577"> "</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">department</span><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">dept</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> }</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>Once set up correctly, the first time an LDAP user logs into Yearning, the corresponding LDAP attribute information will automatically be updated to Yearning's user data, eliminating the need for the administrator to set it separately.</p>
</div></template>


