<template><div><div class="hint-container warning">
<p class="hint-container-title">Warning</p>
<p>Regarding OSCExpr audit rule considerations:</p>
<p>In versions of Yearning prior to 3.0.0, pt-osc execution instructions were standardized through forced pt-osc parameter names. This created several issues:</p>
<ol>
<li>The inability to extend parameters</li>
<li>Difficulty in understanding the relationship between parameters in Yearning and pt-osc</li>
<li>Lack of support for migration tools other than pt-osc</li>
</ol>
</div>
<p>Due to the above reasons, Yearning 3.0.0 introduces the OSCExpr parameter, replacing the previous pt-osc parameter rules.</p>
<p>By introducing general variables, the aim is to cater to all scenarios for DDL migration tool requirements. The added general variables are as follows:</p>
<div class="language-shell line-numbers-mode" data-ext="shell" data-title="shell"><button class="copy" title="Copy code" data-copied="Copied"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">1.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">  $SQL</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">       Corresponds</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> to</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> the</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> execution</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> order</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">s SQL statement  </span></span>
<span class="line"><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">2.  $ADDR      Corresponds to the execution order</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">s</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> data</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> source</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> address</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">3.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">  $PORT</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">      Corresponds</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> to</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> the</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> execution</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> order</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">s data source port</span></span>
<span class="line"><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">4.  $USER      Corresponds to the execution order</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">s</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> data</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> source</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> user</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">5.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">  $PASSWORD</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  Corresponds</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> to</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> the</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> execution</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> order</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">s data source password</span></span>
<span class="line"><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">6.  $SCHEMA    Corresponds to the execution order</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">s</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> database</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> name</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">  </span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">7.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">  $TABLE</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">     Corresponds</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> to</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> the</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> execution</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> order</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">s table name</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>After the changes, if you need to invoke pt-osc commands in DDL statements, you can write it as follows:</p>
<div class="language-shell line-numbers-mode" data-ext="shell" data-title="shell"><button class="copy" title="Copy code" data-copied="Copied"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">pt-online-schema-change</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> --alter</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> $SQL</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> --user=</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">$USER</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> --password=</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">$PASSWORD</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> --host=</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">$ADDR</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> --port=</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">$PORT</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">,D=</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">$SCHEMA</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">,t=</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">$TABLE</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> --execute</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>The system will automatically populate the related data from the corresponding order into the associated variables, eliminating the need for manual input.</p>
<p>If you wish to use other migration tools, you simply need to substitute the relevant general variables into the appropriate command (for instance, gh-ost).</p>
<p><strong>To view the execution results, click the OSC Progress tab in the order details of the execution order.</strong></p>
</div></template>


