<template><div><h3 id="notice" tabindex="-1"><a class="header-anchor" href="#notice"><span>Notice</span></a></h3>
<p>The Yearning installation package includes a Dockerfile, allowing you to directly build and package it into an image.</p>
<p>When launching the container, you can pass the database address and secret key using environment variables.</p>
<p>If you are using Docker separately, please create the database first and set the character set to <strong>utf8mb4</strong>.</p>
<p>Here's how to do it:</p>
<div class="language-bash line-numbers-mode" data-ext="bash" data-title="bash"><button class="copy" title="Copy code" data-copied="Copied"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">## Initialize the database</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">docker</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> run</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> --rm</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -it</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -p8000:8000</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -e</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> SECRET_KEY=</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">$SECRET_KEY</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -e</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> MYSQL_USER=</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">$MYSQL_USER</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -e</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> MYSQL_ADDR=</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">$MYSQL_ADDR</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -e</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> MYSQL_PASSWORD=</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">$MYSQL_PASSWORD</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -e</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> MYSQL_DB=</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">$Yearning_DB</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -e</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Y_LANG=zh_CN</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> yeelabs/yearning</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">/opt/Yearning install</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">## Start Yearning</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">docker</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> run</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -d</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -it</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -p8000:8000</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -e</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> SECRET_KEY=</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">$SECRET_KEY</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -e</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> MYSQL_USER=</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">$MYSQL_USER</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -e</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> MYSQL_ADDR=</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">$MYSQL_ADDR</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -e</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> MYSQL_PASSWORD=</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">$MYSQL_PASSWORD</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -e</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> MYSQL_DB=</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">$Yearning_DB</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -e</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Y_LANG=zh_CN</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> yeelabs/yearning</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="docker-compose-recommended-installation" tabindex="-1"><a class="header-anchor" href="#docker-compose-recommended-installation"><span>Docker-compose (Recommended Installation)</span></a></h2>
<p>In the <code v-pre>docker</code> directory of the installation package/source code repository, execute <code v-pre>docker-compose up -d</code> to start.</p>
</div></template>


